DEFAULT_PROVIDER_BASE_URL = "http://localhost:11434/v1"
DEFAULT_PROVIDER_API_KEY = ""
DEFAULT_PROVIDER_MODEL = "gpt-4o"
DEFAULT_CHATSERVER_URL = "http://localhost:18279"
DEFAULT_BOT_PASSWORD = "outo-10team-bot-2026"
DEFAULT_CONTAINER_IMAGE = "archlinux:latest"
DEFAULT_TEAM_COUNT = 10
